name: remote ssh command
on:
  release:
    types: [published]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh deploy_ci commands with key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo /your/path/to/deploy-django/deploy_ci.sh <appname>